services:
  redis:
    image: redislabs/redismod
  pg:
    image: postgres:16
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=dumbpass
    volumes:
      - ./instance:/var/lib/postgresql/data
  omnyom:
    build:
      context: .
      target: builder
    image: omnyomapp
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    secrets:
      - dev_database_secret
      - test_database_secret
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - pg
      - redis
  worker:
    image: omnyomapp
    command: ["dramatiq app.initializers.dramatiq_redis app.operations.refresh"]
    volumes:
      - .:/code
    secrets:
      - dev_database_secret
      - test_database_secret
    depends_on:
      - omnyom
      - pg
      - redis
  cron-worker:
    image: omnyomapp
    command: ["cron -f"]
    volumes:
      - .:/code
      - ./crontabs:/var/spool/cron/crontabs/
    secrets:
      - dev_database_secret
      - test_database_secret
    depends_on:
      - pg
      - redis
secrets:
  dev_database_secret:
    file: ./secrets/dev_database_secret.txt
  test_database_secret:
    file: ./secrets/test_database_secret.txt
