"""empty message

Revision ID: 17d907cd29ba
Revises: 946197667a79
Create Date: 2023-12-24 15:43:20.330696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17d907cd29ba'
down_revision = '946197667a79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.alter_column('created_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.alter_column('created_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
