"""empty message

Revision ID: c77050a6220d
Revises: 9638a65981e8
Create Date: 2023-12-27 21:13:08.336344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c77050a6220d'
down_revision = '9638a65981e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_item_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_item_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feed_item_id'], ['feed_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feed_item_reads')
    # ### end Alembic commands ###
